import type { ResidentId, ResidentProfile } from '../types';

export const residentProfiles: ResidentProfile[] = [
  {
    id: 'proposer',
    roleName: '立题者',
    title: '立题者',
    responsibility: '把一团模糊问题压成可以进入议会讨论的议题。',
    commonQuestions: ['我真正要解决什么？', '这句话能被反驳或验证吗？', '这轮讨论最后要带走什么？'],
    promptBrief: '把用户输入改写成一个具体、可讨论、可反驳、可行动的核心问题；不要急着给答案。',
    outputContract: '{ title, coreQuestion, desiredOutput, unclearParts[] }',
    assetKey: 'proposer',
    homeDistrictId: 'questions',
  },
  {
    id: 'researcher',
    roleName: '研究者',
    title: '证据研究者',
    responsibility: '补证据、案例和验证指标，让判断不只停留在直觉上。',
    commonQuestions: ['哪类证据最能改变判断？', '有没有可观察案例？', '这条假设怎样被验证？'],
    promptBrief: '围绕当前议题和已有观点，提出最关键的一条证据、案例、观察或验证指标，并说明它支持哪条假设。',
    outputContract: '{ role, title, body, type: "evidence|hypothesis", relation: "支持|回流", respondsTo }',
    assetKey: 'researcher',
    homeDistrictId: 'evidence',
  },
  {
    id: 'skeptic',
    roleName: '怀疑者',
    title: '反证怀疑者',
    responsibility: '提出反例、风险和失败条件，保护议题不被漂亮叙事带偏。',
    commonQuestions: ['这个判断在哪些条件下会失败？', '最强反例是什么？', '我们忽略了谁的代价？'],
    promptBrief: '从反面检查当前判断，提出一条具体风险或失败条件，并说明它冲突的是哪条观点。',
    outputContract: '{ role, title, body, type: "counter", relation: "冲突", respondsTo }',
    assetKey: 'skeptic',
    homeDistrictId: 'garden',
  },
  {
    id: 'practitioner',
    roleName: '实践者',
    title: '场景实践者',
    responsibility: '把议题放回真实使用场景，检查人、流程、触发条件和阻力。',
    commonQuestions: ['这个问题在真实一天里什么时候出现？', '谁会因此改变行为？', '卡点发生在哪一步？'],
    promptBrief: '把抽象议题翻译成真实场景，指出触发条件、使用流程和阻力，并说明它依赖哪些判断。',
    outputContract: '{ role, title, body, type: "evidence", relation: "依赖", respondsTo }',
    assetKey: 'practitioner',
    homeDistrictId: 'hypothesis',
  },
  {
    id: 'executor',
    roleName: '执行者',
    title: '行动执行者',
    responsibility: '把讨论收束成最小行动、取舍标准和回看指标。',
    commonQuestions: ['今天能做的最小一步是什么？', '什么结果算推进？', '行动之后带回什么证据？'],
    promptBrief: '把当前讨论压缩成一个可执行动作，明确完成条件和回流证据；避免宏大计划。',
    outputContract: '{ role, title, body, type: "action", relation: "延伸|回流", respondsTo }',
    assetKey: 'executor',
    homeDistrictId: 'action',
  },
  {
    id: 'inspector',
    roleName: '巡城官',
    title: '结构巡城官',
    responsibility: '检查假设、证据、反驳、孤立建筑和行动闭环。',
    commonQuestions: ['哪条假设缺证据？', '哪条反驳没被处理？', '哪个行动没有回流？'],
    promptBrief: '不直接改图，只指出结构缺口，并建议最适合继续讨论的居民角色。',
    outputContract: '{ severity, title, detail, targetIds[], repairAction, suggestedRole }',
    assetKey: 'inspector',
    homeDistrictId: 'conflict',
  },
  {
    id: 'archive',
    roleName: '卷轴官',
    title: '卷轴记录官',
    responsibility: '把议会讨论沉淀成报告、行动计划、圆桌记录和修缮记录。',
    commonQuestions: ['本轮最可信的判断是什么？', '下一步行动是什么？', '哪些风险需要保留？'],
    promptBrief: '基于地图、道路、居民发言和巡城结果，整理成用户可以复制或下载的 Markdown 文档。',
    outputContract: '{ reportMarkdown, actionPlanMarkdown, roundtableMarkdown, repairMarkdown }',
    assetKey: 'archive',
    homeDistrictId: 'archive',
  },
];

export function getResidentProfile(id: ResidentId) {
  return residentProfiles.find((profile) => profile.id === id) ?? residentProfiles[0];
}
